# Generated by Django 4.2.9 on 2024-01-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastPushDatetime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_success_dt', models.DateTimeField(help_text='Datetime till which videos were pushed to store.')),
            ],
        ),
        migrations.CreateModel(
            name='VideoStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_created_on', models.DateTimeField(auto_now_add=True, help_text='Datetime when the video is added to store.')),
                ('title', models.TextField(help_text='Title of the video.')),
                ('description', models.TextField(help_text='Description of the video.')),
                ('publish_datetime', models.DateTimeField(help_text='Date when video was published.')),
                ('thumbnails', models.JSONField(default=dict, help_text='links of thumbnails of different dimensions.')),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeCreds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the api key.', max_length=50)),
                ('api_key', models.CharField(help_text='Api key for youtube service.', max_length=80)),
            ],
        ),
    ]
