# Generated by Django 4.2.9 on 2024-01-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videostore',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the video.', null=True),
        ),
    ]
