# Generated by Django 4.2.9 on 2024-01-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0002_alter_videostore_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubecreds',
            name='api_service_name',
            field=models.CharField(default='youtube', help_text='Service name used for yt client.', max_length=30),
        ),
        migrations.AddField(
            model_name='youtubecreds',
            name='api_version',
            field=models.CharField(default='v3', help_text='API version.', max_length=20),
        ),
    ]
