# Generated by Django 4.2.9 on 2024-01-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0003_youtubecreds_api_service_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubecreds',
            name='is_exhausted',
            field=models.BooleanField(default=False, help_text='stores if quota is exceeded for the day.'),
        ),
    ]
